# fly.toml file generated for protohackers-problem-0 on 2023-01-06T14:38:01+01:00

app = "protohackers-problem-0"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  build-target = "production"

  [build.args]
    PORT="8080"

[deploy]
  strategy = "immediate"

[experimental]
  allowed_public_ports = []
  auto_rollback = false

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = "8080"
